### PR TITLE
chore: update to 0.10.1

### PR DESCRIPTION
**Pull request by kaihowl**

### CODE REVIEW

**Review by brettmilford — APPROVED** [review]
Complied and tested - it works for me.

**Comment by kaihowl** [comment]
@reviewers @galgalesh Please have a look. :)

**Comment by kaihowl** [comment]
@brettmilford How do I get the right people to review this and merge the PR? If I overlooked some step and work is missing from my end, please let me know. I am happy to follow up if needed.

**Comment by brettmilford** [comment]
@kaihowl I don't know sorry :) I was hoping by commenting it might prod someone.

**Comment by daboross** [comment]
https://github.com/snapcrafters says to tag @ reviewers

@reviewers I'm not the writer of this PR, but it looks like it's still the latest Alacritty release, and it'd be great to have an up-to-date Alacritty on Ubuntu!

**Review by galgalesh — APPROVED** [review]
Thanks! Apologies for the delay, we are currently low on members who can review pull requests.

**Pull request merged**
