### PR TITLE
Update to latest version

### PR DESCRIPTION
**Pull request by spyridonas**

### CODE REVIEW

**Comment by popey** [comment]
Thanks for the PR. Apologies nobody got to it sooner. Upstream are up to 12.3 now, so if you ninja edit this to 12.3, I'll happily approve it.

**Comment by spyridonas** [comment]
I did the 🥷 edit!

**Comment by spyridonas** [comment]
Hello, since the build passed can you accept this pr ?
Thanks

**Review by popey — APPROVED** [review]
LGTM!

**Pull request merged**
